# Generated by Django 5.1.5 on 2025-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Баннерное изображение'),
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('moderation', 'На модерации'), ('archive', 'Архив')], default='moderation', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
