# Generated by Django 5.1.5 on 2025-02-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('moderation', 'На модерации'), ('archive', 'Архив')], default='moderation', max_length=20, verbose_name='Статус'),
        ),
    ]
